### ISSUE TITLE
It works for camelCase but not for hypen-case

### ISSUE THREAD

**Issue by lustremedia** [fussinatto/vscode-vue-peek#12]
Goto does work for camelCase components, but is not working when the component is written with a hypen.

helloWorld <= works
hello-world <= No definition found for "hello-world"

I am using vscode insight 1.48.0, it used to work on previous versions ...

**Comment by EarthmanWeb** [comment]
I have the opposite experience, on my system (Mac OS) it works for hyphen-case but not for CamelCase (???)

vue@2.6.12
nuxt@v2.14.0
vscode: 1.51.0

Mojave 10.14.6 (18G6020)

Hope this helps!

**Comment by EarthmanWeb** [comment]
Hello @fuzinato 

Happy New Year!  Just circling back on this, as it came up again today...

My vue components are named in my filesystem using hyphen-case (for readibility), but they are called in code using CamelCase (for clarity and syntax highlighting)

When I use this extension, it works when I change the code to use hyphen case as well, but this project is huge, and, as mentioned, then we will lose the syntax formatting that comes with the CamelCase definitions.

I could take a hack at trying to implement this in a PR, but it would be helpful to know what files to start in, please.

Thanks!

**Comment by fuzinato** [comment]
Hi all,

sadly is not working because of Vetur plugin( if you disable vetur plugin and try peeking/goto, it should work as intended). Recently Vetur also implemented "Go To Definition" that overrides this plugin and it is causing this inconsistency. Sadly I haven't found solution yet but will keep looking.

Thanks
