### ISSUE TITLE
Can you support js file

### ISSUE THREAD

**Issue by kinanson** [fussinatto/vscode-vue-peek#2]
I like this excellent extension but if you can also support js file in the .vue file.That is Wonderful.

**Comment by fuzinato** [comment]
Hi kinanson,
there are 2 settings options that allows you to customize targeted files and language in which the plugin is activated. By default they look like this:
```
  "vue-peek.supportedLanguages": [
    "vue"
  ],
 "vue-peek.targetFileExtensions": [
    ".vue",
  ]
```
You can add support for any file extension you like. Go to settings, search for _vue-peek_ and add **.js** extension to _targetFileExtensions_ option. This way the plugin will also search .js files.
I hope this answers your question.

**Comment by kinanson** [comment]
You are right.thanks
