### ISSUE TITLE
Feature request: handle `@` syntax

### ISSUE THREAD

**Issue by ffxsam** [fussinatto/vscode-vue-peek#4]
This syntax is used in some of the official `vue-init` templates:

```js
import Hello from '@/components/Hello'
```

`@` points to `src/`. It would be great if vue-peek supported this and could jump to the component source.

**Comment by fuzinato** [comment]
Thanks, i'll look into that

**Comment by ffxsam** [comment]
Thanks! Not sure if it makes sense to read the project's webpack config to see where `@` is resolving to:

https://github.com/vuejs-templates/webpack/blob/17ed63b1b3a0eaaebd3f593c08c32107a7cb7e01/template/build/webpack.base.conf.js#L28

**Comment by lesonky** [comment]
you can use a `jsconfig.json` to fix this;
ps: my file like this,and it works well:

```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "es6",
        "allowSyntheticDefaultImports": true,
        "baseUrl": ".",
        "paths": {
            "@/*": ["src/*"],
            "src/*": ["src/*"],
            "assets/*": ["src/assets/*"],
            "components/*": ["src/components/*"],
            "views/*": ["src/views/*"],
            "styles/*": ["src/styles/*"],
            "api/*": ["src/api/*"],
            "utils/*": ["src/utils/*"],
            "store/*": ["src/store/*"],
            "router/*": ["src/router/*"],
            "mock/*": ["src/mock/*"],
            "vendor/*": ["src/vendor/*"],
            "fonts/*": ["src/fonts/*"]
        }
    },
    "exclude": ["dist"]
}
```

**Comment by ffxsam** [comment]
Great, this works! I've modified mine to just include the path `"@/*": ["src/*"]`
