### ISSUE TITLE
Ignore files

### ISSUE THREAD

**Issue by iamstevendao** [fussinatto/vscode-vue-peek#5]
Can I ignore some folders or files while peeking?  
![screenshot_6](https://user-images.githubusercontent.com/15044203/33864725-42082aee-df42-11e7-9efc-0549a505b792.png)  
the files in folder `.meteor\local\...` should not be included because they are built files.

**Comment by fuzinato** [comment]
This feature is not built in for this plugin, but you could add folders to  "files.exclude" in your vscode settings.
